### ISSUE TITLE
Add support for multiple interceptors, for logging/profiling, etc

### ISSUE THREAD

**Issue by mariusGundersen** [mattiasnordqvist/Web-Anchor#69]
It would be nice if we could add multiple interceptors to the ProxyGenerator, for example for logging and profiling around the HttpClient.

**Comment by mattiasnordqvist** [comment]
You could do this by adding `DelegatingHandler`s in the HttpClient. Would this work for you? I think the main reason I would rather do it this way is because I don't want to expose my dependency on dynamicproxy to much. If we would expose it, it would be a breaking change to replace dynamicproxy with anything cooler/nicer/better.

```csharp
WebAnchor.Api.For<IMyApi>(new HttpClient(new LoggingHandler(new HttpClientHandler()));
```



```csharp
public class LoggingHandler : DelegatingHandler
    {
        public LoggingHandler(HttpMessageHandler innerHandler)
            : base(innerHandler)
        {
        }

        protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
          // Log in some way here... 

            var response = await base.SendAsync(request, cancellationToken);

          // ...or maybe here
            return response;
        }
    }
```

**Comment by mariusGundersen** [comment]
Neat, yes, that solves my problem
