### ISSUE TITLE
Separate nuget for attributes

### ISSUE THREAD

**Issue by mariusGundersen** [mattiasnordqvist/Web-Anchor#71]
It's common and useful to have a separate nuget package for the interfaces and attributes, and one nuget with the implementation that depends on that nuget. This would be useful for web-anchor too. This way the attributes could be installed in a multi-project solution, but the implementation only installed in one project. The implementation is also likely to change more often than the attributes, so it is easier to maintain when projects only reference the attributes, not the implementation.

**Comment by mattiasnordqvist** [comment]
Hmm. Never considered this. Don't think I've seen it. Is it really that common? :) 

... trying to understand... 
So the benefit is that you don't have to reference the implementation-nuget in some of your projects, right? So in the projects where you declare your `IApi`'s you reference the interface-nuget, and where you instantiate them you reference both packages?

I am seeing to points that make me not wanna go this way. Convince me otherwise. :)
* Both dlls will end up in the distributable solution-build anyway, so it has no effect in the end.
* Is this really worth the hassle of maintaining to nuget-packages and the implementation-nuget's dependency on the interface-nuget?

**Comment by mariusGundersen** [comment]
One case we are looking into is a micro service architecture, where the service can create a nuget package of it's client. This way it could publish the client which contains the interface and dtos, and the interface is decorated with the attributes, but the user of the client will have to pick which implementation it wants to use. It means that a project can have many clients to different micro services, each which references the attributes nuget, but not the implementation. This way we don't get conflicts when installing multiple clients, each of which uses a different version of web-anchor, but since they use the same version of the web-anchor-attributes project it's not a problem.

**Comment by mattiasnordqvist** [comment]
2 years later... did you solve this some other way?

**Comment by mattiasnordqvist** [comment]
We are finally coming around to do this. #118
