### ISSUE TITLE
Payload forgotten handling

### ISSUE THREAD

**Issue by carl-berg** [mattiasnordqvist/Web-Anchor#8]
Had a _misuse problem_ with a **POST** action where i forgot to set `[Payload]` attribute for the one parameter the method had. In a unit test it causes a NullReferenceException but in my MVC async context i got a hanging behavior. Not sure why. I think the lib should handle this like a POST without body and just throw the object into the querystring or route (which it seemed like it did).

**Comment by mattiasnordqvist** [comment]
We have multiple issues like this, most of them are not reported yet, but #10 is also a good example of how we could supply validation to make it easier for the developer to spot his mistakes. We should discuss how we validate the definition of an api. At the creation of the api or when a method is actually called? I can see an issue with validating at api creation time. At that point you don't necessarily know which requestfactory or responsebuilder will be used later on, or how it will be configured, since they can be changed or replaced after the api has been created. However, it seems unecessary to validate the api for each request changed. The requestfactory and the responebuilder should probably provide their own validation methods, and they could cache their validation results if they are costly to produce.

**Comment by mattiasnordqvist** [comment]
And true, a post without a body is surely ok, so it must be possible.

**Comment by mattiasnordqvist** [comment]
Payload has changed name to Content

**Comment by mattiasnordqvist** [comment]
The validation should also check the type of value attributed as Content. To me, it doesn't make sense to pass a primitive type, a string or a list, as it cannot be turned into a proper json object. Must be an object or a dictionary<string, anything>

**Comment by mattiasnordqvist** [comment]
No Content-attribute -> empty content!
Check the HTTP Spec to see if headers should be modified.

**Comment by carl-berg** [comment]
Seems like POST and PUT should (since specification is a bit vague) be allowed without Body and with header lengths set appropriately.
http://stackoverflow.com/questions/1233372/is-an-http-put-request-required-to-include-a-body
http://stackoverflow.com/questions/7323958/are-put-and-post-requests-required-expected-to-have-a-request-body

**Comment by mattiasnordqvist** [comment]
I think we should allow anything that HttpClient allows. It would be nice to not shrinken the nr of available use-cases, forcing people to leave web anchor behind

**Comment by carl-berg** [comment]
:+1: I agree

**Comment by carl-berg** [comment]
Ran into this one again today. Made a custom content serializer that checks if Content is missing,and if so, just returns null for Content. Seems to work fine...

**Comment by mattiasnordqvist** [comment]
Released in 1.0.20
